#Electricity consumption
#Week 3:
Assignment: Electricity Consumption Data Analysis with NumPy
Problem Statement
You are provided with electricity consumption data (in kWh) for a household measured daily over 4 months (120 days).
 The daily consumption values range between 200 kWh (minimum) and 600 kWh (maximum).
Your task is to simulate the dataset using NumPy and perform an in-depth analysis of the household’s electricity consumption.

Tasks (Do all 10)
1. Generate the Dataset
Use numpy.random.randint() to simulate 120 daily consumption values between 200 and 600 kWh.
Store the data in a NumPy array called consumption.

2. Basic Statistics
Calculate the mean, median, minimum, maximum, and standard deviation of daily consumption.

3. Identify Extremes
Find the day number(s) with the highest and lowest consumption.

4. Monthly Splitting
Divide the dataset into 4 months (30 days each).
Store each month’s data in a separate NumPy array.

5. Monthly Analysis
For each month: calculate the total consumption and average daily consumption.

6. Weekly Analysis
Reshape or split the data into weeks of 7 days (ignore the extra 4 days at the end).
Compute the weekly totals and weekly averages.

7. Overall Consumption Trend
Calculate the cumulative consumption across the 120 days.
Display the first 10 values of the cumulative sum.

8. Anomaly Detection
Define anomalies as days where consumption is 2 standard deviations above or below the mean.
Identify the day numbers that are anomalies.

In [16]:
import numpy as np
import pandas as pd
# 1. Generate the Dataset
# Use numpy.random.randint() to simulate 120 daily consumption values between 200 and 600 kWh.
# Store the data in a NumPy array called consumption.

np.random.seed(42)
days = np.arange(1 , 121)
consumption = np.random.randint(200 , 600, size=120)

print("Days:", days)
print("\nConsumption:", consumption)

Days: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120]

Consumption: [302 548 470 306 271 388 220 302 321 414 530 287 572 299 559 351 330 349
 508 457 543 493 585 391 476 360 513 221 452 435 544 248 258 369 387 470
 389 374 250 563 254 443 519 330 506 334 220 528 366 473 587 288 515 213
 441 464 545 252 585 539 291 566 463 234 405 280 249 559 587 201 589 253
 305 459 509 390 417 243 361 401 469 550 503 470 414 451 389 495 412 407
 436 537 566 252 479 416 451 387 579 240 356 214 500 264 544 526 208 543
 328 335 262 338 280 591 362 488 578 460 430 240]

In [31]:
# Store the data in a NumPy array called consumption.
data = pd.DataFrame({
    "Days" : days, 
    "Consumption (kWh)" : consumption

})

data

     Days  Consumption (kWh)
0       1                302
1       2                548
2       3                470
3       4                306
4       5                271
..    ...                ...
115   116                488
116   117                578
117   118                460
118   119                430
119   120                240

[120 rows x 2 columns]

In [17]:
#2. Basic Statistics
# Calculate the mean, median, minimum, maximum, and standard deviation of daily consumption.

Mean = np.mean(consumption)
Median = np.median(consumption)
Minimum = np.min(consumption)
Maximum = np.max(consumption)
Std = np.std(consumption)

print("Mean_Consumption:", round(Mean, 2), "kWh")
print("Median_Cosumption:", round(Median, 2),"kWh")
print("Minimum_Consumption:", round(Minimum, 2),"kWh")
print("Maximum_Consumption:", round(Maximum, 2),"kWh")
print("Std_Consumption:", round(Std, 2),"kWh")

Mean_Consumption: 408.49 kWh
Median_Cosumption: 414.0 kWh
Minimum_Consumption: 201 kWh
Maximum_Consumption: 591 kWh
Std_Consumption: 115.2 kWh

In [18]:
#3. Identify Extremes
# Find the day number(s) with the highest and lowest consumption.
            # np.argmax() → returns the index of the largest value. # +1 for human-readable day count 
            # np.argmin() → returns the index of the smallest value. # +1 for human-readable day count
            # np.max() → return the actual highest values.
            # np.min() → return the actual lowest values.

#highest = np.where(consumption == np.max(consumption))[0] + 1
#print('Days with Highest Consumption:', highest)

#lowest = np.where(consumption == np.min(consumption))[0] + 1
#print('Days with Highest Consumption:', lowest)


highest_consumption_day = np.argmax(consumption)
lowest_consumption_day = np.argmin(consumption)

print("Highest Consumption Day Number:", highest_consumption_day + 1)
print("Lowest Consumption Day Number:", lowest_consumption_day + 1)

Highest Consumption Day Number: 114
Lowest Consumption Day Number: 70

In [19]:
# 4. Monthly Splitting
# Divide the dataset into 4 months (30 days each).


Month = np.array_split(consumption, 4)

print(Month)

[array([302, 548, 470, 306, 271, 388, 220, 302, 321, 414, 530, 287, 572,
       299, 559, 351, 330, 349, 508, 457, 543, 493, 585, 391, 476, 360,
       513, 221, 452, 435], dtype=int32), array([544, 248, 258, 369, 387, 470, 389, 374, 250, 563, 254, 443, 519,
       330, 506, 334, 220, 528, 366, 473, 587, 288, 515, 213, 441, 464,
       545, 252, 585, 539], dtype=int32), array([291, 566, 463, 234, 405, 280, 249, 559, 587, 201, 589, 253, 305,
       459, 509, 390, 417, 243, 361, 401, 469, 550, 503, 470, 414, 451,
       389, 495, 412, 407], dtype=int32), array([436, 537, 566, 252, 479, 416, 451, 387, 579, 240, 356, 214, 500,
       264, 544, 526, 208, 543, 328, 335, 262, 338, 280, 591, 362, 488,
       578, 460, 430, 240], dtype=int32)]

In [20]:
# Store each month’s data in a separate NumPy array.
month1, month2, month3, month4 = np.array_split(consumption, 4)
print("First_Month:", month1)
print("Second_Month:", month2)
print("Third_Month:", month3)
print("Forth_Month:", month4)

First_Month: [302 548 470 306 271 388 220 302 321 414 530 287 572 299 559 351 330 349
 508 457 543 493 585 391 476 360 513 221 452 435]
Second_Month: [544 248 258 369 387 470 389 374 250 563 254 443 519 330 506 334 220 528
 366 473 587 288 515 213 441 464 545 252 585 539]
Third_Month: [291 566 463 234 405 280 249 559 587 201 589 253 305 459 509 390 417 243
 361 401 469 550 503 470 414 451 389 495 412 407]
Forth_Month: [436 537 566 252 479 416 451 387 579 240 356 214 500 264 544 526 208 543
 328 335 262 338 280 591 362 488 578 460 430 240]

In [21]:
# 5. Monthly Analysis
# For each month: calculate the total consumption and average daily consumption.

#print('Monthly Total Consumptions:')
#monthly_total_consump = [print(month.sum()) for month in months] 

#print('\nAverage Consumptions per Month:')
#monthly_avg_consump = [print(month.mean()) for month in months]

print("Monthly Total Consumption\n")

print("First-Month-Total-Consumption:", np.sum(month1),"kWh")
print("Second-Month-Total-Consumption:", np.sum(month2),"kWh")
print("Third-Month-Total-Consumption:", np.sum(month3),"kWh")
print("Forth-Month-Total-Consumption:", np.sum(month4),"kWh")

print("\nAverage Daily Consumption\n")

print("First-Month-Average-Daily-Consumption:", round(np.mean(month1), 2),"kWh")
print("Second-Month-Average-Daily-Consumption:", round(np.mean(month2), 2),"kWh")
print("Third-Month-Average-Daily-Consumption:", round(np.mean(month3), 2),"kWh")
print("Forth-Month-Average-Daily-Consumption:", round(np.mean(month4), 2), "kWh")

Monthly Total Consumption

First-Month-Total-Consumption: 12253 kWh
Second-Month-Total-Consumption: 12254 kWh
Third-Month-Total-Consumption: 12322 kWh
Forth-Month-Total-Consumption: 12190 kWh

Average Daily Consumption

First-Month-Average-Daily-Consumption: 408.43 kWh
Second-Month-Average-Daily-Consumption: 408.47 kWh
Third-Month-Average-Daily-Consumption: 410.73 kWh
Forth-Month-Average-Daily-Consumption: 406.33 kWh

In [22]:
# 6. Weekly Analysis
# Reshape or split the data into weeks of 7 days (ignore the extra 4 days at the end).
# Compute the weekly totals and weekly averages.

#Weekly = consumption.reshape(7, 17)
#1. 
#Weekly = np.array_split(consumption,17)
#print(Weekly)

#2.
#week1,week2,week3,week4,week5,week6,week7,week8,week9,week10,week11,week12,week13,week14,week15,week16,week17 = np.split(consumption[:119], 17)
#print(week1, week2, week3, week4, week5, week6, week7, week8, week9, week10, week11, week12, week13, week14, week15, week16, week17)

#3.
#weeks = np.split(consumption[:119], 17)
#week1, week2, week3, week4, week5, week6, week7, week8, week9, week10, week11, week12, week13, week14, week15, week16, week17 = weeks
#print(weeks)

#4.
weeks = np.split(consumption[:119], 17)
print(weeks)

#5. 
#weeks = np.split(consumption[:119], 17)
#for i, week in enumerate(weeks, start=1):
 #   print(f"Week {i}: {week}")

#print("Remaining day:", consumption[119:])

[array([302, 548, 470, 306, 271, 388, 220], dtype=int32), array([302, 321, 414, 530, 287, 572, 299], dtype=int32), array([559, 351, 330, 349, 508, 457, 543], dtype=int32), array([493, 585, 391, 476, 360, 513, 221], dtype=int32), array([452, 435, 544, 248, 258, 369, 387], dtype=int32), array([470, 389, 374, 250, 563, 254, 443], dtype=int32), array([519, 330, 506, 334, 220, 528, 366], dtype=int32), array([473, 587, 288, 515, 213, 441, 464], dtype=int32), array([545, 252, 585, 539, 291, 566, 463], dtype=int32), array([234, 405, 280, 249, 559, 587, 201], dtype=int32), array([589, 253, 305, 459, 509, 390, 417], dtype=int32), array([243, 361, 401, 469, 550, 503, 470], dtype=int32), array([414, 451, 389, 495, 412, 407, 436], dtype=int32), array([537, 566, 252, 479, 416, 451, 387], dtype=int32), array([579, 240, 356, 214, 500, 264, 544], dtype=int32), array([526, 208, 543, 328, 335, 262, 338], dtype=int32), array([280, 591, 362, 488, 578, 460, 430], dtype=int32)]

In [23]:
#Compute the weekly totals and weekly averages.

#print('Weekly Total Consumptions:')
#weekly_total = [print(week.sum()) for week in weekly]

#print('\nAverage Consumptions per Week:')
#weekly_avg = [print(week.mean()) for week in weekly]

# Compute weekly totals
weekly_totals = np.sum(weeks, axis=1)
weekly_totals = np.round(weekly_totals, 2)

# Compute weekly averages
weekly_averages = np.mean(weeks, axis=1)

weekly_averages = np.round(weekly_averages, 2)

print("Weekly_Total:",weekly_totals )

#print(weekly_totals)

print("\nWeekly_Average:",weekly_averages)

#print(weekly_averages)


# Display results
#for i in range(full_weeks):
 #   print(f"Week {i+1}")
   # print("Daily Consumption:", weekly_data[i])
 #   print("Weekly Total:", weekly_totals[i])
 #   print("Weekly Average:", round(weekly_averages[i], 2))
 #   print()

Weekly_Total: [2505 2725 3097 3039 2693 2743 2803 2981 3241 2515 2922 2997 3004 3088
 2697 2540 3189]

Weekly_Average: [357.86 389.29 442.43 434.14 384.71 391.86 400.43 425.86 463.   359.29
 417.43 428.14 429.14 441.14 385.29 362.86 455.57]

In [24]:
# 7. Overall Consumption Trend
# Calculate the cumulative consumption across the 120 days.
# Display the first 10 values of the cumulative sum.# Example 120-day consumption dataset

# Calculate cumulative consumption
cumulative_consumption = np.cumsum(consumption)

# Display results
print("Daily Consumption:")
print(consumption)

print("\nCumulative Consumption:")
print(cumulative_consumption)

Daily Consumption:
[302 548 470 306 271 388 220 302 321 414 530 287 572 299 559 351 330 349
 508 457 543 493 585 391 476 360 513 221 452 435 544 248 258 369 387 470
 389 374 250 563 254 443 519 330 506 334 220 528 366 473 587 288 515 213
 441 464 545 252 585 539 291 566 463 234 405 280 249 559 587 201 589 253
 305 459 509 390 417 243 361 401 469 550 503 470 414 451 389 495 412 407
 436 537 566 252 479 416 451 387 579 240 356 214 500 264 544 526 208 543
 328 335 262 338 280 591 362 488 578 460 430 240]

Cumulative Consumption:
[  302   850  1320  1626  1897  2285  2505  2807  3128  3542  4072  4359
  4931  5230  5789  6140  6470  6819  7327  7784  8327  8820  9405  9796
 10272 10632 11145 11366 11818 12253 12797 13045 13303 13672 14059 14529
 14918 15292 15542 16105 16359 16802 17321 17651 18157 18491 18711 19239
 19605 20078 20665 20953 21468 21681 22122 22586 23131 23383 23968 24507
 24798 25364 25827 26061 26466 26746 26995 27554 28141 28342 28931 29184
 29489 29948 30457 30847 31264 31507 31868 32269 32738 33288 33791 34261
 34675 35126 35515 36010 36422 36829 37265 37802 38368 38620 39099 39515
 39966 40353 40932 41172 41528 41742 42242 42506 43050 43576 43784 44327
 44655 44990 45252 45590 45870 46461 46823 47311 47889 48349 48779 49019]

In [25]:
# Display the first 10 values of the cumulative sum

# Display first 10 values
print(cumulative_consumption[:10])

[ 302  850 1320 1626 1897 2285 2505 2807 3128 3542]

In [26]:
#8. Anomaly Detection
#Define anomalies as days where consumption is 2 standard deviations above or below the mean.


# Define anomaly thresholds
upper_bound = Mean + (2 * Std)
lower_bound = Mean - (2 * Std)


print("\nUpper Bound:", round(upper_bound, 2))
print("Lower Bound:", round(lower_bound, 2))

Upper Bound: 638.9
Lower Bound: 178.09

In [27]:
# Identify the day numbers that are anomalies.

anomaly_days = np.where(
    (consumption > upper_bound) | (consumption < lower_bound))[0] + 1 

print("\nAnomaly Days:", anomaly_days)

Anomaly Days: []

In [28]:
print(days)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120]

In [29]:
print(consumption)

[302 548 470 306 271 388 220 302 321 414 530 287 572 299 559 351 330 349
 508 457 543 493 585 391 476 360 513 221 452 435 544 248 258 369 387 470
 389 374 250 563 254 443 519 330 506 334 220 528 366 473 587 288 515 213
 441 464 545 252 585 539 291 566 463 234 405 280 249 559 587 201 589 253
 305 459 509 390 417 243 361 401 469 550 503 470 414 451 389 495 412 407
 436 537 566 252 479 416 451 387 579 240 356 214 500 264 544 526 208 543
 328 335 262 338 280 591 362 488 578 460 430 240]

In [32]:
data

     Days  Consumption (kWh)
0       1                302
1       2                548
2       3                470
3       4                306
4       5                271
..    ...                ...
115   116                488
116   117                578
117   118                460
118   119                430
119   120                240

[120 rows x 2 columns]